version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/camposss/go-chat-backend
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo export TAG=$CIRCLE_WORKFLOW_ID >> $BASH_ENV
      - run:
          name: Build Docker Image
          command: |
            make docker TAG=$TAG
      - run: 
          name: Push Docker Image to Hub
          command: |
            make push TAG=$TAG
